# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1ed31502a7e235d1c1f701b66430bfb92809ee1fe5bbe59ccc12d2316ec32dd1188853d44343b9106289e21d0b828d26ff9e42b13b27e800674a8662871be14d

test:
  secret_key_base: ee49fa6d04d3ca657c700d4b9fc5c6e958cef5eea8537c80467da475919ca2f9980700100088abb1514c71366c44eb191843088dad31bc608d3cc0ce82bcebf5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
